name: work_timer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: 5.0.0-release-candidate-5
  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  logger: ^2.0.2+1
  cupertino_onboarding: ^1.2.0
  flutter_animate: ^4.3.0
  simple_circular_progress_bar: ^1.0.2
  collection: ^1.18.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SFCompactRounded
      fonts:
        - asset: assets/fonts/SF-Compact-Rounded-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Compact-Rounded-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Compact-Rounded-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Compact-Rounded-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Compact-Rounded-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Compact-Rounded-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Compact-Rounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Compact-Rounded-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Compact-Rounded-Ultralight.otf
          weight: 200